<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 10/20/2018
 * Time: 2:02 PM
 */

namespace App\Http\Controllers\API;


use App\Decorators\FindShipper\FindShipperDecorator;
use App\Http\Controllers\Requests\API\GetRequest;
use App\Http\Controllers\Requests\API\Shipper\ShipperGetRequest;
use App\Http\Controllers\Requests\API\Shipper\ShipperPatchRequest;
use App\Http\Controllers\Requests\API\Shipper\ShipperPostRequest;

class ShipperController extends APIController
{
    public function __construct(FindShipperDecorator $service)
    {
        parent::__construct($service);
    }

    public function get(ShipperGetRequest $request, ?int $id = null)
    {
        return parent::_get($request, $id);
    }

    public function getAvailable()
    {
        /**
         * @var FindShipperDecorator $shipperService
         */
        $shipperService = $this->service;
        return $shipperService->findRandomShipper();
    }

    public function post(ShipperPostRequest $request)
    {
        return parent::_post($request);
    }

    public function patch(ShipperPatchRequest $request, ?int $id = null)
    {
        return parent::_patch($request, $id);
    }

    public function delete($id)
    {
        return parent::_delete($id);
    }

    public function getAll(GetRequest $request)
    {
        return parent::_getAll($request); // TODO: Change the autogenerated stub
    }
}